### ISSUE TITLE
cannot run `web3` package with version 6.0.0

### ISSUE THREAD

**Issue by WaterSo0910** [jsvisa/blockchain-etl#1]
In [web3 document](https://web3py.readthedocs.io/en/stable/v6_migration.html#removals) , it had removed Parity Module in `v6.x`. I found this problem after I ran `pipenv install` with `web3>=5.0.0` specified in Pipfile, it will install 6.0.0 due to the latest update just few days ago :laughing: . 
Just modify web3 version to `v5.x` would be fine, and  I have tested for `5.31.4` and it's okay now. Btw thanks for this awesome etl tool :muscle:

**Comment by jsvisa** [comment]
Could you please file a PR to modify the Pipfile to limit the version of web3 to less than `<6`?
